

# install bartools
```{r}
# if (!requireNamespace("devtools", quietly = TRUE)) {
#   install.packages("devtools")
# }
# devtools::install_github("DaneVass/bartools", dependencies = TRUE, force = TRUE)
```

# load BARBIE functions
```{r}
library(readxl)
library(purrr)
library(dplyr)
library(dbscan)
library(ggbiplot)
library(gridExtra)
library(ComplexHeatmap)
library(Rtsne)
library(dbscan)
library(rpart)
library(rpart.plot)
library(pROC)
library(sjPlot)
library(glmnet)
library(logistf)


# Specify the directory containing the R files
folder_path <- "/Users/feiliyang/Desktop/Barbie/R"

# List all files in the folder with a .R extension
r_files <- list.files(folder_path, pattern = "\\.R$", full.names = TRUE)

# Load each R file into the R session
for (file in r_files) {
  source(file)
}

```

# library packages

```{r}
# library(bartools)
library(tidyverse)
```

# read in preprocessed dataset and subset into individual treatments
```{r}
dge <- readRDS("dose2.rds")

# simplify barcode labels
rownames(dge) <- gsub("BFP_Barcode", "BC", rownames(dge))
```

## generate ibet and AraC specific datasets
```{r}
ibet <- dge[,which(dge$samples$Treatment == "IBET" | dge$samples$Treatment == "DMSO"| dge$samples$Treatment == "TP0")]
arac <- dge[,which(dge$samples$Treatment == "ARAC" | dge$samples$Treatment == "DMSO"| dge$samples$Treatment == "TP0")]
```

# split dataset into replicates
```{r}
dge.TR1 <- dge[,which(dge$samples$Technical_Replicate == "TR1")]
dge.TR2 <- dge[,which(dge$samples$Technical_Replicate == "TR2")]
```

# density
```{r}
plot(density(log2(dge$counts + 1)))
mean(dge$counts)
max(dge$counts)
```

# create BARBIE
```{r}
AML_bb <- createBarbie(
  counts = dge$counts, 
  metadata = dge$samples,
  color_panel = NULL)

AML_bb <- getTopBar(Barbie = AML_bb, cut_off = 0.95)

sum(AML_bb$is_top)

AML_bb <- trimRow(Barbie = AML_bb, keep_rows = AML_bb$is_top)
```

# test between Tec Reps
```{r}
#trim out TP0
AML_TPx <- trimObjectByMetadata(
  Barbie = AML_bb, 
  condition = "Timepoint", specified = "TP0", 
  keep = FALSE) # exclude "immature" celltype from samples

# customize sample groups as you need.
Vector_customized <- AML_TPx$metadata$Technical_Replicate

# Generate tables and create the list
c_tables <- GetContingencyTable(AML_TPx, Vector_customized = Vector_customized)
#print the first 5 contingency table
lapply(c_tables[1:5], function(x) {knitr::kable(x)})

# Apply test, and get Bias group
AML_TPx <- GetOccBiasGroup(Barbie = AML_TPx, contingency_table_ls = c_tables)

kableExtra::kable(AML_TPx$Bias_Occ)
table(AML_TPx$Bias_Occ$group)

flag <- AML_TPx$Bias_Occ$group != "Unbiased"
failed_occ <-trimRow(Barbie = AML_TPx, keep_rows = flag)

PlotBiasVsRank(Barbie = AML_TPx, passing_data = "contribution")

PlotBiasVsRank(Barbie = AML_TPx, passing_data = "output")

PlotBiasVsRank(Barbie = AML_TPx, passing_data = "rank")

plot(density(AML_TPx$Bias_Occ$pvalue))
```

# DMSO only - homo
```{r}
#trim out TP0
AML_DMSO <- trimObjectByMetadata(
  Barbie = AML_bb, 
  condition = "Treatment", specified = "DMSO", 
  keep = TRUE) # only include
```

## Sampling within Pseudo-Groups

Fixed Sample Size

running on server

## tSNE

```{r tsne dmso}
# Set an appropriate perplexity value (e.g., num_samples / 3)
perplexity_value <- min(30, floor(ncol(AML_bb$CPM) / 3))

tsne_results <- (AML_bb$CPM + 1) %>% 
  t() %>% 
  log2() %>% 
  Rtsne::Rtsne(perplexit = perplexity_value)
tsne_coords <- tsne_results$Y
tsne_coords <- as.data.frame(tsne_coords)

ggplot(tsne_coords) +
  geom_point(aes(x = V1, y = V2, col = AML_bb$metadata$Treatment)) +
  labs(x = "t-SNE Dimension 1", y = "t-SNE Dimension 2", col = "Mouse") +
  theme(aspect.ratio = 1)

lapply(
  AML_bb$metadata %>% ncol() %>% seq(), 
  function(i) {
    col_fac <- colnames(AML_bb$metadata)[i]
    ggplot(tsne_coords) +
    geom_point(aes(x = V1, y = V2, col = AML_bb$metadata[[i]])) +
    labs(x = "t-SNE Dimension 1", y = "t-SNE Dimension 2", color = col_fac) +
      theme_classic() +
    theme(aspect.ratio = 1)
  }
  )
```


