---
title: "preprocessing_barbieQ"
author: "LF"
date: "2025-04-03"
output: workflowr::wflow_html
output_dir: ../../docs/bartools_dose_escalation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Dependencies

```{r load library}
library(readxl)
library(magrittr)
library(dplyr)
library(tidyr) # for pivot_longer
library(tibble) # for rownames_to _column
library(knitr) # for kable()
library(ggplot2)
library(patchwork)
library(scales)
library(ggVennDiagram)
library(ComplexHeatmap)
library(limma)
library(edgeR)

library(SummarizedExperiment)
library(SEtools)
library(S4Vectors)
library(devtools)

```

# Install barbieQ - devel

```{r install barbieQ}
devtools::install_github("Oshlack/barbieQ")

library(barbieQ)
```

# Read data

Sourced from: [(https://zenodo.org/badge/713176761.svg)](https://zenodo.org/doi/10.5281/zenodo.10896642)

```{r read counts}
dge <- readRDS("../../data/bartools_dose_escalation/dose2.rds")

# simplify barcode labels
rownames(dge) <- gsub("BFP_Barcode", "BC", rownames(dge))

```

# Save to a barbieQ obejct

```{r review metadata}
## check sample metadata
# dge$samples$Treatment %>% table()
# dge$samples %>% class()
# lapply(dge$samples, function (j) {table(j)})
```

```{r create barbieQ}
AML <- barbieQ::createBarbieQ(
  object = dge$counts, 
  sampleMetadata = dge$samples[, c("Treatment", "Strategy", "Technical_Replicate", "Dose", "Timepoint")])
metadata(AML)<- list(
  "Experiment" = "Dose_escalation_2",
  "Celltype" = "MLL-AF9",
  "Library" = "SPLINTR_BFP_V1"
  )
```

# Tag top barcodes

```{r tag top}
dim(AML)
colData(AML)$sampleMetadata
## find minimum group size
targets <- as.data.frame(AML$sampleMetadata) %>% 
  mutate(Group = paste0(Treatment, Strategy, Dose))
targets$Group %>% table()

## select sample to consider, exclude TP0 when tagging
AML <- barbieQ::tagTopBarcodes(
  barbieQ = AML, 
  activeSamples = AML$sampleMetadata$Treatment != "TP0", 
  nSampleThreshold = 2
  )

rowData(AML)$isTopBarcode$isTop %>% table()
```

```{r vis tag}
barbieQ::plotBarcodePareto(barbieQ = AML)
barbieQ::plotBarcodeSankey(barbieQ = AML)
```

# Barcode Correlation

```{r barcode correlation}
png("../../output/bartools_dose_escalation/bar_cor.png", width = 2000, height = 2000, res = 300)
barbieQ::plotBarcodePairCorrelation(barbieQ = AML, cpmThresh = 2^12.5)
dev.off()
```

```{r cluster barcodes}
## cluster barcoes
AML <- barbieQ::clusterCorrelatingBarcodes(barbieQ = AML, cpmThresh = 2^12.5)

## check out clusters
identifiedCluster <- rowData(AML)$barcodeCorrelatedCluster %>% as.data.frame()

AML_agg <- SEtools::aggSE(AML, by = identifiedCluster$cluster, assayFun = "max")

row_sums <- rowSums(assay(AML))

max_rows_per_cluster <- tapply(
  rownames(identifiedCluster),  # Row names
  identifiedCluster$cluster,  # Grouping variable
  function(rows) rows[which.max(row_sums[rows])]  # Get row with max sum per cluster
)

max_rows_df <- data.frame(cluster = names(max_rows_per_cluster), rowname = unlist(max_rows_per_cluster))

max_rows_df <-max_rows_df[rownames(AML_agg), ]

rownames(AML_agg) <- max_rows_df$rowname

## recreate barbieQ
AML_agg <- createBarbieQ(
  object = assay(AML_agg), sampleMetadata = AML$sampleMetadata)
metadata(AML_clone) <- metadata(AML)
```


```{r plot clusters}

identifiedCluster$cluster[identifiedCluster$cluster < 0] <- -1

plot3 <- ggplot(data = identifiedCluster) +
  geom_histogram(data = filter(identifiedCluster, cluster > 0), 
                 aes(x = cluster, fill = as.factor(cluster)), 
                 binwidth = 1, color = "white") +
  theme_classic() +
  scale_x_continuous(breaks = 1:12, labels = 1:12) +
  theme(aspect.ratio = 1, legend.position = "none")

ggsave("../../output/bartools_dose_escalation/cluster_hist.png", plot = plot3, width = 3, height = 3, dpi = 300)

identifiedCluster <- identifiedCluster %>% 
  mutate(logMeanCPM = log2(rowMeans(assays(AML)$CPM)+1))

plot4 <- ggplot(data = identifiedCluster) +
  geom_point(aes(x = cluster, y = logMeanCPM),
             color = "grey", shape = 1, size = 4) +
  geom_point(data = filter(identifiedCluster, cluster > 0),
             aes(x = cluster, 
                 y = logMeanCPM,
                 color = factor(cluster)),
             shape = 1, size = 4, stroke = 1) +
  scale_x_continuous(breaks = 1:12, labels = 1:12) +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = "none")

ggsave("../../output/bartools_dose_escalation/cluster_mean.png", plot = plot4, width = 3, height = 3, dpi = 300)
```

# Tag top barcode after collapsing

```{r tag after cor}
AML_agg <- tagTopBarcodes(
  barbieQ = AML_agg,
  activeSamples = AML_agg$sampleMetadata$Treatment != "TP0", 
  nSampleThreshold = 2)

barbieQ::plotBarcodePareto(barbieQ = AML_agg)
barbieQ::plotBarcodeSankey(barbieQ = AML_agg)

ggsave("../../output/bartools_dose_escalation/pareto.png", 
       plot = barbieQ::plotBarcodePareto(barbieQ = AML_agg), 
       width = 10, height = 7, dpi = 300)
ggsave("../../output/bartools_dose_escalation/sankey.png", 
       plot = barbieQ::plotBarcodeSankey(barbieQ = AML_agg), 
       width = 5, height = 5, dpi = 300)

```

# Heatmap

```{r hp}
png(filename = "../../output/bartools_dose_escalation/HP_unfilter.png", width = 2000, height = 2000, res = 300)
Heatmap(name = "logCPM",
  matrix = log2(assays(AML_agg)$CPM + 1), 
  row_title = paste0(nrow(AML_agg), " Barcodes"), 
  show_row_names = FALSE, show_column_names = FALSE)
dev.off()

AML_top <- AML_agg[rowData(AML_agg)$isTopBarcode$isTop,]

png(filename = "../../output/bartools_dose_escalation/HP_filtered.png", width = 2000, height = 2000, res = 300)
Heatmap(name = "logCPM",
  matrix = log2(assays(AML_top)$CPM + 1), 
  row_title = paste0(nrow(AML_top), " Barcodes"), 
  show_row_names = FALSE, show_column_names = FALSE)
dev.off()
```

# Save rds

```{r save rds}
save(AML, AML_agg, AML_top, file = "../../output/bartools_dose_escalation/AML_barbieQ.rda")


load("../../output/bartools_dose_escalation/AML_barbieQ.rda")
```

# Top10

```{r}
tagTop10 <- function(col) {
  ranks <- rank(-col)
  # summary(ranks)
  isTop <- ranks <= 10
  # summary(isTop)
  return(isTop)
}

tester <- tagTop10(assays(AML_agg)$CPM[,1])
summary(tester)

colTags <- lapply(as.data.frame(assays(AML_agg)$CPM), 
                  function(col) tagTop10(col))
colTagMat <- do.call(cbind, colTags)
colTagVec <- rowSums(colTagMat) >= 1
summary(colTagVec)

AML_agg_top10 <- AML_agg
rowData(AML_agg_top10)$isTopBarcode <- DataFrame(isTop = colTagVec)
summary(rowData(AML_agg_top10)$isTopBarcode$isTop)


ggsave("../../output/bartools_dose_escalation/pareto_top10.png", 
       plot = barbieQ::plotBarcodePareto(barbieQ = AML_agg_top10), 
       width = 10, height = 7, dpi = 300)
ggsave("../../output/bartools_dose_escalation/sankey_top10.png", 
       plot = barbieQ::plotBarcodeSankey(barbieQ = AML_agg_top10), 
       width = 5, height = 5, dpi = 300)
```

