---
title: "explore_correlating_barcodes"
author: "LF"
date: "2025-02-25"
output: workflowr::wflow_html
output_dir: ../../docs/WuC
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Dependencies

```{r load library}
library(readxl)
library(magrittr)
library(dplyr)
library(tidyr) # for pivot_longer
library(tibble) # for rownames_to _column
library(knitr) # for kable()
library(ggplot2)
library(patchwork)
library(scales)
library(ggVennDiagram)
library(ComplexHeatmap)
library(limma)

library(barbieQ)
```

# Load barbieQ

```{r load barbieQ}
## install barbieQ from github if haven't already
# install.packages("/Users/feiliyang/Desktop/barbieQ/", repos = NULL, type = "source")
library(barbieQ)
```

# Load Processed Data

```{r load rda}
## no need to load this again
# getwd()
# load("../../output/WuC/tagged_bq_min.rda")
## truncate barcodes for "tops"
## no need to run this again.
# ZG66_bq_min$isTop$vec %>% sum()
# ZG66_bq_min <- barbieQ::subsetBarcodes(
#   barbieQ = ZG66_bq_min, 
#   retainedRows = ZG66_bq_min$isTop$vec
#   )
```

# Barcode Correlation

```{r barcode correlation}
## this is just for small test run
# flag <- rep(FALSE, 1667)
# flag[1:10] <- TRUE
# tester <- barbieQ::subsetBarcodes(barbieQ = ZG66_bq_min, retainedRows = flag)
# barbieQ::plotBarcodePairCorrelation(barbieQ = tester)
# 
# png(file = "barCluster.png")
# tester <- barbieQ::clusterCorrelatingBarcodes(
#   barbieQ = tester, corCutoff = 0.5, dataCutoff = 1)
# dev.off()

## plot correlation
## I sent the following lines to run as background job, where the working directory is the R.project, unlike the wd of this Rmd document.
# ggplot2::ggsave(
#   filename = "./analysis/WuC/barCor.png",
#   plot = barbieQ::plotBarcodePairCorrelation(barbieQ = ZG66_bq_min)
#   )
# 
# png(file = "./analysis/WuC/barCluster.png")
# ZG66_bq_min <- barbieQ::clusterCorrelatingBarcodes(
#   barbieQ = ZG66_bq_min, dataCutoff = 2^10)
# dev.off()
# saveRDS(object = ZG66_bq_min, file = "./output/WuC/ZG66_bq_min.rds")

getwd()
ZG66_bq_min <- readRDS("../../output/WuC/ZG66_bq_min.rds")
ZG66_bq_min$BarcodeCluster$corCluster %>% summary()
```

```{r plot barcode clusters, fig.width=10, fig.height=10}
## pca analysis on barcodes
pca_result <- prcomp((ZG66_bq_min$CPM), scale. = TRUE)
pca_data <- pca_result$x %>% as.data.frame()
pca_data$Cluster <- ZG66_bq_min$BarcodeCluster$corCluster
pca_data$Cluster %>% summary()
## check the cluster names are numeric
is.numeric(pca_data$Cluster)
## group all those unclustered (unlikely to be repeated barcodes) together
pca_data$Cluster[pca_data$Cluster < 0] <- -1
## rename the clusters and unclustered groups
pca_data <- pca_data %>% 
  mutate(group = ifelse(Cluster < 0, "unclustered \n barcodes",
                          paste0("cluster ", Cluster))) %>% 
  mutate(group = factor(group, 
                        levels = c("unclustered \n barcodes", 
                                   paste0("cluster ", 1:37))))
## plot unclustered barcodes by grey
## plot each cluster by a unique color in the second layer
## facet group (Cluster) to plot each one by one
plot1 <- ggplot(pca_data) +
  geom_point(data = pca_data, 
             aes(x = PC1, y = PC3),
             color = "grey", shape = 1, size = 4, stroke = 1) +
  geom_point(data = filter(pca_data, Cluster != -1),
             aes(x = PC1, y = PC3, color = factor(Cluster)),
             shape = 1, size = 4, stroke = 1) +
  facet_wrap(~group) +
  theme_classic() +
  theme(legend.position = "none", aspect.ratio = 1)
## save into the current folder
ggsave("./cluster_pca_facet.png", plot = plot1, width = 10, height = 10, dpi = 300)
## disable facet
## plot all clusters together in one plot but still color coded
plot2 <- ggplot(pca_data) +
  geom_point(data = pca_data, 
             aes(x = PC1, y = PC3),
             color = "grey", shape = 1, size = 4, stroke = 1) +
  geom_point(data = filter(pca_data, Cluster != -1),
             aes(x = PC1, y = PC3, color = factor(Cluster)),
             shape = 1, size = 4, stroke = 1) +
  theme_classic() +
  theme(legend.position = "none", aspect.ratio = 1)
## save the big pcs plot
ggsave("./cluster_pca.png", plot = plot2, width = 3, height = 3, dpi = 300)
```

```{r merge barcodes}
ZG66_bq_min_clone <- barbieQ::collapseBarcodes(
  barbieQ = ZG66_bq_min, groupArray = ZG66_bq_min$BarcodeCluster)
## This is a pkg bug - need fix later
ZG66_bq_min_clone$isTop$vec <- as.vector(ZG66_bq_min_clone$isTop$vec)
barbieQ::plotBarcodeProportion(barbieQ = ZG66_bq_min)
barbieQ::plotBarcodeProportion(barbieQ = ZG66_bq_min_clone)

summary(ZG66_bq_min_clone$isTop$vec)

is.vector(ZG66_bq_min_clone$isTop$vec)
is.vector(ZG66_bq_min$isTop$vec)

ZG66_bq_min_clone$isTop$vec %>% str()
ZG66_bq_min$isTop$vec %>% str()
```

```{r cluster distribution}
## 37 barcodes repeated in 12 clones
## averagely 5 barcodes per clone
plot3 <- ggplot(data = pca_data) +
  geom_histogram(data = filter(pca_data, Cluster > 0), 
                 aes(x = Cluster, fill = as.factor(Cluster)), 
                 binwidth = 1, color = "white") +
  theme_classic() +
  scale_x_continuous(breaks = 1:12, labels = 1:12) +
  theme(aspect.ratio = 1, legend.position = "none")

ggsave("./cluster_hist.png", plot = plot3, width = 3, height = 3, dpi = 300)

pca_data <- pca_data %>% 
  mutate(logMeanCPM = log2(rowMeans(ZG66_bq_min$CPM)+1))

plot4 <- ggplot(data = pca_data) +
  geom_point(aes(x = Cluster, y = logMeanCPM),
             color = "grey", shape = 1, size = 4) +
  geom_point(data = filter(pca_data, Cluster > 0),
             aes(x = Cluster, 
                 y = logMeanCPM,
                 color = factor(Cluster)),
             shape = 1, size = 4, stroke = 1) +
  scale_x_continuous(breaks = 1:12, labels = 1:12) +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = "none")

ggsave("./cluster_mean.png", plot = plot4, width = 3, height = 3, dpi = 300)
```

