---
title: "TOC tester"
author: "LF"
date: "2025-01-11"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

```{=html}
<style>
.scroll-plot {
    width: 1000px;
    height: 600px;
    overflow-y: scroll;
    overflow-x: scroll;
}
</style>
```

```{r dummy, echo=FALSE}
# dummy data
data <- data.frame(
  METRIC = paste('var', 1:20),
  VAL = runif(10),
  stringsAsFactors = FALSE
)
```

```{r results = 'asis', echo=FALSE}
# automatically generate <style> block of css for each tab
tab_number <- 1:nrow(data)
tab_color <- "#CCCCCC"
css <- sprintf(".color-tabs>.nav-pills>li:nth-child(%d){background:%s;}", tab_number, tab_color)
css <- paste(css, collapse = "\n")
css <- paste("<style>", css, "</style>")
cat(css)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Dependencies

This is the section for loading dependencies.

## C2

This is content for section C2.

### Sub2.1

Content for subsection 2.1.

### Sub2.2

Content for subsection 2.2.
