## Load Library
```{r load library}
library(ggplot2)
library(patchwork)
library(ComplexHeatmap)

library(dplyr)
library(tidyr)
library(magrittr)

library(devtools)
```

## Read Data

```{r read data}
EV1 <- read.csv(
  "/Users/feiliyang/Desktop/published_analysis_tools/DEBRA/paper_data/msb199195-sup-0004-datasetev1.csv", 
  row.names = 1)
```

## Quality Check

```{r quality check}
EV1 <- as.matrix(EV1)
is.numeric(EV1)
plot(density(log2(EV1 + 1)))
dim(EV1)
sampleName <- colnames(EV1)
sampleName

## check library size of each sample
libSize <- colSums(EV1)

ggplot(
  data.frame(libSize = libSize,
             sample = sampleName)) + 
  geom_point(aes(x = seq_along(sampleName), y = libSize)) +
  geom_text(
    aes(x = seq_along(sampleName), y = libSize, label = sample), 
    vjust = -1, size = 3, angle = 45)

## check only null samples
ggplot(
  data.frame(libSize = libSize[1:14], 
             sample = sampleName[1:14])) + 
  geom_point(aes(x = seq_len(14), y = libSize)) +
  geom_text(
    aes(x = seq_len(14), y = libSize, label = sample), 
    vjust = -1, size = 3, angle = 45)

## check "P1" and "P2" sample - Barcode count distribution
poolAB <- EV1[, c("P1", "P2")] %>% 
  data.frame() %>% 
  mutate(Mix = (P1 + P2)/2)
## reshape data into long format
poolAB_long <- poolAB %>%
  pivot_longer(cols = c("P1", "P2", "Mix"), names_to = "Variable", values_to = "Value")
ggplot(poolAB_long, aes(x = log2(Value +1))) +
  geom_histogram() +
  facet_wrap(~ Variable, ncol=1) +
  labs(x = "log2 Count+1", y = "Frequency") +
  theme_minimal()

## check null samples
nulls <- c("null_660.1","null_660.2","null_330.1","null_330.2","m_null_20.p35.1","m_null_20.p35.2")
nullSamples <- EV1[, nulls]
ggplot(data.frame(libSize = colSums(nullSamples),
                  sample = colnames(nullSamples))) + 
  geom_point(aes(x = seq_along(nulls), y = libSize)) +
  geom_text(aes(x = seq_along(nulls), y = libSize, label = sample), 
            vjust = -1, size = 2, angle=20) +
  scale_y_continuous(limits = c(0, NA))
```

## Load Barbie

```{r load Barbie}
# install_github("Oshlack/Barbie", force = TRUE)
library(Barbie)
sampleName
```

## Prerpocessing

### Extracting Conditions

```{r extracting sample conditions}
## extract P1P2, nulls and perturbs
Subset <- gsub("m_null_.*", "perturb", sampleName)
Subset <- gsub("null.*", "null", Subset)
Subset <- gsub("P.*", "premix", Subset)

## extract cell size (Barcode size, i.e. total number of Barcodes in each sample)
BarcodeSize <- gsub(".*null_(\\d+)\\..*", "\\1", sampleName)
BarcodeSize <- gsub("(P\\d)", "", BarcodeSize)

## extract perturbation level in the perturb samples
Perturbation <- gsub(".*p(\\d+).*", "\\1", sampleName)
Perturbation <- gsub("[A-Za-z]+.*", "0", Perturbation)

## extract technical rep
TechRep <- gsub(".*\\.(\\d)", "\\1", sampleName)
TechRep <- gsub("P\\d", "1", TechRep)

## combine these into a data.frame
Design <- data.frame(
  Subset = factor(Subset, levels = c("premix", "null", "perturb")),
  BarcodeSize = as.numeric(BarcodeSize) * 1000,
  Perturbation = as.numeric(Perturbation) / 100,
  TechRep = factor(TechRep)
)
```

```{r preprocessing barbie}
## takes all samples and design and create Barbie object
EV1_bb <- Barbie::createBarbie(object = EV1, target = Design)
## tag top Barodes across all samples, all!
EV1_bb <- Barbie::tagTopBarcodes(Barbie = EV1_bb)
EV1_bb$isTop$vec %>% sum()
Barbie::plotBarcodePareto(Barbie = EV1_bb)
Barbie::plotBarcodeSankey(Barbie = EV1_bb)
## hem out bottom Barcodes
EV1_bb <- Barbie::subsetBarcodes(Barbie = EV1_bb, retainedRows = EV1_bb$isTop$vec)

## cannot plot heatmap for now, with more than 2k Barcodes
# Barbie::plotBarbieHeatmap(Barbie = EV1_bb)

## plot sample pair correlation
Barbie::plotSamplePairCorrelation(Barbie = EV1_bb)
```

```{r pca all, fig.width=7, fig.height=6}
## PCA of Barbie
pca <- prcomp(t(EV1_bb$CPM))
v1v2 <- pca$x[, 1:2]
pcaDF <- cbind(v1v2, EV1_bb$metadata)
pcaDF$BarcodeSize <- factor(
  ifelse(is.na(pcaDF$BarcodeSize), "Missing", pcaDF$BarcodeSize),
  levels = c(sort(unique(pcaDF$BarcodeSize[!is.na(pcaDF$BarcodeSize)])), "Missing")
)
pcaDF$BarcodeSize[which(is.na(pcaDF$BarcodeSize))] <- "NA"

ggplot(pcaDF, aes(x=PC1, y=PC2)) +
  geom_point(
    aes(
      size=BarcodeSize,
      shape=Subset, 
      color=Perturbation)) +
  theme_classic() + 
  theme(aspect.ratio = 1)

```

### PoolAB

```{r}
EV1_poolAB <- Barbie::subsetSamplesByMetadata(
  Barbie = EV1_bb, factor = "Subset", specifiedConditions = "premix", keep = TRUE
)
poolAB <- EV1_poolAB$assay %>% 
  mutate(Ratio = (P1+1) / (P2+1))
truth <- vector(length = nrow(EV1_poolAB$assay))
truth[poolAB$Ratio > 10] <- "A"
truth[poolAB$Ratio < 0.1] <- "B"
length(truth)
sum(poolAB$Ratio == 1)
sum(poolAB$Ratio > 10)
sum(poolAB$Ratio < 0.1)
sum(EV1_poolAB$assay$P1 != 0)
sum(EV1_poolAB$assay$P2 != 0)

ggplot(poolAB, aes(y = log1p(P1), x = log10(Ratio))) +
  geom_point()
ggplot(poolAB, aes(y = log1p(P2), x = log10(Ratio))) +
  geom_point()
```


### Null+Perturb

```{r remove premix samples, fig.width=7, fig.height=6}
EV1_mix <- Barbie::subsetSamplesByMetadata(
  Barbie = EV1_bb, factor = "Subset", specifiedConditions = "premix", keep = FALSE)
EV1_mix <- Barbie::tagTopBarcodes(Barbie = EV1_mix, minTopFrequency = 2)
EV1_mix$isTop$vec %>% sum()

truth_mix <- truth[EV1_mix$isTop$vec]
length(truth_mix)

EV1_mix <- Barbie::subsetBarcodes(Barbie = EV1_mix, retainedRows = EV1_mix$isTop$vec)


## PCA of Barbie
pca <- prcomp(t(EV1_mix$CPM))
v1v2 <- pca$x[, 1:2]
pcaDF <- cbind(v1v2, EV1_mix$metadata)
pcaDF$BarcodeSize <- factor(
  pcaDF$BarcodeSize,
  levels = sort(unique(pcaDF$BarcodeSize))
)

ggplot(pcaDF, aes(x=PC1, y=PC2)) +
  geom_point(
    aes(
      size=BarcodeSize,
      shape=Subset, 
      color=Perturbation)) +
  theme_classic() + 
  theme(aspect.ratio = 1)
```

### Null

```{r null samples, fig.width=7, fig.height=6}
EV1_null <- Barbie::subsetSamplesByMetadata(
  Barbie = EV1_bb, factor = "Subset", specifiedConditions = "null", keep = TRUE)
EV1_null <- Barbie::tagTopBarcodes(Barbie = EV1_null, minTopFrequency = 2)
EV1_null$isTop$vec %>% sum()
EV1_null <- Barbie::subsetBarcodes(Barbie = EV1_null, retainedRows = EV1_null$isTop$vec)

## PCA of Barbie
pca <- prcomp(t(EV1_null$CPM))
v1v2 <- pca$x[, 1:2]
pcaDF <- cbind(v1v2, EV1_null$metadata)
pcaDF$BarcodeSize <- factor(
  pcaDF$BarcodeSize,
  levels = sort(unique(pcaDF$BarcodeSize))
)

ggplot(pcaDF, aes(x=PC1, y=PC2)) +
  geom_point(
    aes(
      size=BarcodeSize,
      shape=Subset, 
      color=Perturbation)) +
  theme_classic() + 
  theme(aspect.ratio = 1)
```

### Perturb

```{r perturb samples, fig.width=7, fig.height=6}
EV1_perturb <- Barbie::subsetSamplesByMetadata(
  Barbie = EV1_bb, factor = "Subset", specifiedConditions = "perturb", keep = TRUE)
EV1_perturb <- Barbie::tagTopBarcodes(Barbie = EV1_perturb, minTopFrequency = 2)
EV1_perturb$isTop$vec %>% sum()
EV1_perturb <- Barbie::subsetBarcodes(Barbie = EV1_perturb, retainedRows = EV1_perturb$isTop$vec)

## PCA of Barbie
pca <- prcomp(t(EV1_perturb$CPM))
v1v2 <- pca$x[, 1:2]
pcaDF <- cbind(v1v2, EV1_perturb$metadata)
pcaDF$BarcodeSize <- factor(
  pcaDF$BarcodeSize,
  levels = sort(unique(pcaDF$BarcodeSize))
)

ggplot(pcaDF, aes(x=PC1, y=PC2)) +
  geom_point(
    aes(
      size=BarcodeSize,
      shape=Subset, 
      color=Perturbation)) +
  theme_classic() + 
  theme(aspect.ratio = 1)
```

## Random Sampling

### Fun: k vs. k sampling

```{r}
Sample_Groups <- function(Barbie, sampleSize = 3) {
  pool <- Barbie$assay %>% ncol() %>% seq_len()
  
  ## First sampling without replacement
  group1Samples <- sample(pool, size = sampleSize, replace = FALSE)
  ## Remove the first sample from the pool
  remainingPool <- setdiff(pool, group1Samples)
  ## Second sampling without replacement from the remaining pool
  group2Samples <- sample(remainingPool, size = sampleSize, replace = FALSE)
  ## Create a group vector
  groupArray <- vector("character", length = length(pool))
  groupArray[group1Samples] <- "group1"
  groupArray[group2Samples] <- "group2"
  ## Store in Barbie Object
  Barbie$metadata <- data.frame(Group = groupArray, Barbie$metadata)
  ## select samples to be compared - group1 vs group2
  sample_bb <- Barbie::subsetSamplesByMetadata(
    Barbie = Barbie, 
    factor = "Group",
    specifiedConditions = c("group1", "group2")) 
  ## set up target
  mytargets <- sample_bb$metadata[,"Group", drop=FALSE]
  ## model design matrix
  mydesign <- mytargets %>%
    with(model.matrix(~0 + Group))
  
  ## apply test for proportion
  sample_bb <- Barbie::testBarcodeBias(
    Barbie = sample_bb,
    targets = mytargets,
    sampleGroups = "Group"
  )
  sample_bb$testBarcodes$diffProp_Group$results$direction %>% table()
  # extract p.values and FPR
  nBarcode <- nrow(sample_bb$assay)
  nPositive_Prop <- sum(sample_bb$testBarcodes$diffProp_Group$results$direction != "n.s.")
  FPR_Prop <- nPositive_Prop / nBarcode
  
  #penalized logistic madel
  sample_bb <- Barbie::testBarcodeBias(
    Barbie = sample_bb,
    targets = mytargets,
    sampleGroups = "Group",
    method = "diffOcc",
    regularization = "firth"
  )
  nPositive_Occ <- sum(sample_bb$testBarcodes$diffOcc_Group$results$direction != "n.s.")
  FPR_Occ <- nPositive_Occ / nBarcode
  
  return(
    list(FPR_Occ = FPR_Occ,
         FPR_Prop = FPR_Prop,
         adj.p_Occ = sample_bb$testBarcodes$diffOcc_Group$results$adj.p.value,
         adj.p_Prop = sample_bb$testBarcodes$diffProp_Group$results$adj.p.value,
         groupArray = groupArray)
  )
  
}
```

```{r random sampling nulls}

tester <- Sample_Groups(Barbie = EV1_null, sampleSize = 4)



```

### Fun: N loop k vs. k

```{r}
Loop_Samples <- function(Barbie, sampleSize = 3, loop_times = 100) {
  
  FPR_Occ_list <- list(length = loop_times)
  FPR_Prop_list <- list(length = loop_times)
  
  adj.p_Occ_list <- list(length = loop_times)
  adj.p_Prop_list <- list(length = loop_times)
  
  groupArray_list <- list(length = loop_times)
  
  for(i in 1:loop_times) {
    results_i <- Sample_Groups(Barbie = Barbie, sampleSize = sampleSize)
    
    FPR_Occ_list[[i]] <- results_i$FPR_Occ
    FPR_Prop_list[[i]] <- results_i$FPR_Prop
    
    adj.p_Occ_list[[i]] <- results_i$adj.p_Occ
    adj.p_Prop_list[[i]] <- results_i$adj.p_Prop
    
    groupArray_list[[i]] <- results_i$groupArray
  }
  
  FPR <- data.frame(
    N_Samples = rep(sampleSize, loop_times),
    Occ = FPR_Occ_list %>% unlist(),
    Prop = FPR_Prop_list %>% unlist()
    )
  rownames(FPR) <- paste0("loop_", seq_len(nrow(FPR)))
  
  adj.pvalues <- data.frame(
    N_Samples = rep(sampleSize, loop_times),
    Occ = adj.p_Occ_list %>% unlist(),
    Prop = adj.p_Prop_list %>% unlist()
    )
  
  groupInfo <- do.call(rbind, groupArray_list) %>% as.data.frame()
  colnames(groupInfo) <- rownames(Barbie$metadata)
  rownames(groupInfo) <- paste0("loop_", seq_len(nrow(groupInfo)))
  
  return(
    list(
      FPR = FPR,
      pvalues = adj.pvalues,
      groupInfo = groupInfo
      )
    )

}
```

### Fun: k ranging from 3 to half pool

```{r}

  ## input
  Barbie <- EV1_null
  loop_times <- 100

  num_samples <- ncol(Barbie$CPM)
  end_sampling <- floor(num_samples / 2)
  
  # stop running loop if end_sampling <= 3
  if(num_samples < 3) {
    return("not enough samples!")
  }
  
  # set.seed(42) # for reproducibility
  
  # run the loops
  suppressMessages({
    all_loops <- lapply(3:end_sampling, function(n) {
      Loop_Samples(
        Barbie = Barbie, sampleSize = n, loop_times = loop_times)
    })
  })
  
  # extract results from the N loops
  all_FPR <- lapply(seq_along(3:end_sampling), function(n) {
    all_loops[[n]]$FPR
  }) 
  
  df_FPR <- do.call(rbind, all_FPR)
  
  df_FPR$N_Samples <- as.factor(df_FPR$N_Samples)
  
  all_pvalue <- lapply(seq_along(3:end_sampling), function(n) {
    all_loops[[n]]$pvalues
  })
  
  df_pvalues <- do.call(rbind, all_pvalue)
  
  df_pvalues$N_Samples <- as.factor(df_pvalues$N_Samples)
  

```

```{r, fig.height=7, fig.width=8}
  gFDR_Occ <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = Occ, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility +
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Occ test, EV1_null samples",
         y = "Prop. barcodes with adj.p.value < 0.05",
         x = "No. samples per group") +
    theme_classic() +
    ylim(c(0,NA))
  
  gFDR_Prop <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = Prop, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Prop test, EV1_null samples",
         y = "Prop. barcodes with adj.p.value < 0.05",
         x = "No. samples per group") +
    theme_classic() +
    ylim(c(0,NA))
  
  gP_Occ <- ggplot(as.data.frame(df_pvalues),
    aes(x = N_Samples, y = -log10(Occ), fill = N_Samples)) +
    geom_boxplot() +
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
    labs(title = "Diff_Occ test, EV1_null samples",
         y = "-log10(adj.p.value)") +
    ylim(c(0,NA)) +
    theme_classic() 
  
  gP_Prop <- ggplot(as.data.frame(df_pvalues),
    aes(x = N_Samples, y = -log10(Prop), fill = N_Samples)) +
    geom_boxplot() +
      geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
    labs(title = "Diff_Prop test, EV1_null samples",
         y = "-log10(adj.p.value)") +
    ylim(c(0,NA)) +
    theme_classic() 
 
  (gFDR_Occ + gFDR_Prop) / (gP_Occ + gP_Prop)
  
  
```

## True Positives

```{r}
EV1_mix <- Barbie::testBarcodeBias(
  Barbie = EV1_mix,
  sampleGroups = "Perturbation",
  designFormula = formula("~0 + Perturbation + BarcodeSize")
)
plotBarcodeBiasScatterPlot(EV1_mix)
testResults <- EV1_mix$testBarcodes$diffProp_Perturbation

plotBarcodeBiasHeatmap(EV1_mix)


halfIndex <- sample(seq_len(nrow(EV1_mix$assay)), 1000)
halfKeep <- rep(FALSE, nrow(EV1_mix$assay))
halfKeep[halfIndex] <- TRUE

EV1_mix_half <- Barbie::subsetBarcodes(Barbie = EV1_mix, retainedRows = halfKeep)
testResults_half <- testResults
testResults_half$results <- testResults$results[halfKeep,,drop=FALSE]
EV1_mix_half$testBarcodes <- NULL
EV1_mix_half$testBarcodes$diffProp_Perturbation <- testResults_half

truth_half <- truth_mix[halfKeep]
length(truth_half)

plotBarcodeBiasHeatmap(EV1_mix_half)


```

### plot HP

```{r}
BBB <- EV1_mix_half
elementName <- "diffProp_Perturbation"
## extract test resilts and information

  testInfo <- BBB$testBarcodes[[elementName]]
  statMat <- testInfo$results
  methodLs <- testInfo$methods
  modelTargets <- testInfo$targets
  ## define a custom color/shape palette for test results
  customShape <- stats::setNames(
    c(21, 24, 23), c(methodLs$contrastLevels, "n.s.")
  )
  customColor <- BBB$factorColors[[elementName]]

  ## customize row annotation
  barcodeAnnotation <- rowAnnotation(
    Direction = statMat$direction,
    Truth = truth_half,
    annotation_name_side = "top",
    annotation_name_gp = grid::gpar(fontsize = 10),
    col = list(
      Direction = customColor,
      Truth = c(A = "#FF5959", B = "#33AAFF")
    ),
    show_legend = TRUE,
    show_annotation_name = TRUE
  )

  ## adjust the order of slices based on contrast levels in the test
  restLevels <- dplyr::setdiff(
    levels(modelTargets[, methodLs$contrastVector]), methodLs$contrastLevels
  )
  levels(modelTargets[, methodLs$contrastVector]) <- c(
    methodLs$contrastLevels, restLevels
  )

  plotBarbieHeatmap(
    Barbie = BBB,
    value = "CPM",
    splitSamples = TRUE,
    targets = modelTargets,
    sampleGroups = methodLs$contrastVector,
    barcodeAnnotation = barcodeAnnotation,
    sampleAnnotation = sampleAnnotation
  )
```

### PoolA

```{r poolA}
table(truth_mix)

EV1_mix_A <- Barbie::subsetBarcodes(
  Barbie = EV1_mix, retainedRows = truth_mix=="A")
EV1_mix_A <- Barbie::tagTopBarcodes(
  EV1_mix_A, minTopFrequency = 2, proportionThreshold = 0.9)
sum(EV1_mix_A$isTop$vec)
EV1_mix_A <- Barbie::subsetBarcodes(
  Barbie = EV1_mix_A, retainedRows = EV1_mix_A$isTop$vec)

repID <- EV1_mix_A$metadata %>% 
  with(paste(BarcodeSize, Perturbation, sep = "_"))

EV1_mix_A <- Barbie::testBarcodeBias(
  Barbie = EV1_mix_A,
  sampleGroups = "Perturbation",
  designFormula = formula("~Perturbation + BarcodeSize"),
  block = repID
)
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_A, xAxis = "avgLogCPM")
N_r <- EV1_mix_A$testBarcodes$diffProp_Perturbation$results$direction %>% table()
N_r
HPa_adj <- Barbie::plotBarcodeBiasHeatmap(EV1_mix_A)
TPR <- N_r["increase"] / sum(N_r)
TPR

## use unadjusted pvalue
pvalue_signif <- EV1_mix_A$testBarcodes$diffProp_Perturbation$results$p.value < 0.05
EV1_mix_A$testBarcodes$diffProp_Perturbation$results$direction[pvalue_signif] <- "increase"
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_A, xAxis = "avgLogCPM", pValuesAdjusted = FALSE)
N_r <- EV1_mix_A$testBarcodes$diffProp_Perturbation$results$direction %>% table()
N_r
HPa <- Barbie::plotBarcodeBiasHeatmap(EV1_mix_A)
TPR <- N_r["increase"] / sum(N_r)
TPR

flag <- which(EV1_mix_A$testBarcodes$diffProp_Perturbation$results$direction == "increase")

CPM_flag <- EV1_mix_A$CPM[flag,]
DF <- data.frame(
  CPM = CPM_flag[2,],
  EV1_mix_A$metadata)

ggplot(DF, aes(x = Perturbation, y = asin(sqrt(CPM/1000000)))) +
  geom_point(aes(size = BarcodeSize))
ggplot(DF, aes(x = Perturbation, y = CPM)) +
  geom_point(aes(size = BarcodeSize))
```

### PoolB

```{r poolB}

EV1_mix_B <- Barbie::subsetBarcodes(
  Barbie = EV1_mix, retainedRows = truth_mix=="B")

EV1_mix_B <- Barbie::tagTopBarcodes(
  EV1_mix_B, minTopFrequency = 2, proportionThreshold = 0.9)
sum(EV1_mix_B$isTop$vec)

EV1_mix_B <- Barbie::subsetBarcodes(
  Barbie = EV1_mix_B, retainedRows = EV1_mix_B$isTop$vec)

# EV1_mix_B <- Barbie::subsetSamplesByMetadata(
#   Barbie = EV1_mix_B, factor = "BarcodeSize", c(660000, 330000), keep = FALSE)

repID <- EV1_mix_B$metadata %>% 
  with(paste(BarcodeSize, Perturbation, sep = "_"))

EV1_mix_B <- Barbie::testBarcodeBias(
  Barbie = EV1_mix_B,
  sampleGroups = "Perturbation",
  designFormula = formula("~Perturbation + BarcodeSize"),
  block = repID
)
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_B, xAxis = "avgLogCPM")
## default resu;t is adjusted pvalue
HPb_adj <- Barbie::plotBarcodeBiasHeatmap(EV1_mix_B)
N_r <- EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction %>% table()
N_r
## use unadjusted pvalue
pvalue_signif <- EV1_mix_B$testBarcodes$diffProp_Perturbation$results$p.value < 0.05
EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction[pvalue_signif] <- "decrease"
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_B, xAxis = "avgLogCPM", pValuesAdjusted = FALSE)
N_r <- EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction %>% table()
N_r
HPb <- Barbie::plotBarcodeBiasHeatmap(EV1_mix_B)
TPR <- N_r["decrease"] / sum(N_r)
TPR


flag <- which(EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction == "decrease")

CPM_flag <- EV1_mix_B$CPM[flag,]
DF <- data.frame(
  CPM = CPM_flag[1,],
  EV1_mix_B$metadata)

ggplot(DF, aes(x = Perturbation, y = asin(sqrt(CPM/1000000)))) +
  geom_point(aes(size = BarcodeSize))
ggplot(DF, aes(x = Perturbation, y = CPM)) +
  geom_point(aes(size = BarcodeSize))



# Create the plot
ggplot(DF, aes(x = Perturbation, y = CPM, group = BarcodeSize, color = as.factor(BarcodeSize))) +
  geom_line() +
  geom_point() +
  labs(
    title = "CPM vs Perturbation for Different Barcode Sizes",
    x = "Perturbation Level",
    y = "CPM",
    color = "Barcode Size"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

# flag <- which(EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction == "n.s.")
# 
# CPM_flag <- EV1_mix_B$CPM[flag,]
# DF <- data.frame(
#   CPM = CPM_flag[1,],
#   EV1_mix_B$metadata)
# 
# ggplot(DF, aes(x = Perturbation, y = asin(sqrt(CPM/1000000)))) +
#   geom_point(aes(size = BarcodeSize))
# ggplot(DF, aes(x = Perturbation, y = CPM)) +
#   geom_point(aes(size = BarcodeSize))
```
### A+B

```{r, fig.width=6, fig.height=8}
HPa %v% HPb
HPa_adj %v% HPb_adj
```
```{r}
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_A, xAxis = "avgLogCPM", pValuesAdjusted = FALSE)
Barbie::plotBarcodeBiasScatterPlot(EV1_mix_B, xAxis = "avgLogCPM", pValuesAdjusted = FALSE)
```

### A Line

```{r , fig.width=10, fig.height=4}
DF_long <- as.data.frame(EV1_mix_A$proportion) %>%
  mutate(Direction = EV1_mix_A$testBarcodes$diffProp_Perturbation$results$direction) %>%
  pivot_longer(cols = -Direction, names_to = "SampleName", values_to = "Prop") 
target_replicated <- bind_rows(replicate(nrow(EV1_mix_A$proportion), EV1_mix_A$metadata, simplify = FALSE)) %>% 
  mutate(
    BarcodeID = rep(paste0("Barcode_", seq_len(nrow(EV1_mix_A$proportion))), each=nrow(EV1_mix_A$metadata))) 
DF_long$Direction %>% table()
DF_long <- bind_cols(DF_long, target_replicated) 


lineA1 <- ggplot(DF_long, 
       aes(x = Perturbation, y = Prop, 
           group = paste(BarcodeSize, BarcodeID), color = Direction)) +
  geom_line(alpha=0.6) +
  geom_point() +
  labs(
    title = "Prop vs Perturbation for Different Barcode and Barcode Sizes",
    x = "Perturbation Level",
    y = "Proportion",
    color = "Direction"
  ) +
  theme_classic() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1),
    aspect.ratio = 1
  ) +
  scale_color_manual(values = EV1_mix_A$factorColors$diffProp_Perturbation)

lineA2 <- ggplot(DF_long, 
       aes(x = Perturbation, y = log2(Prop*1000000+1), 
           group = paste(BarcodeSize, BarcodeID), color = Direction)) +
  geom_line(alpha=0.6) +
  geom_point() +
  labs(
    # title = "Prop vs Perturbation for Different Barcode and Barcode Sizes",
    x = "Perturbation Level",
    y = "log2(CPM+1)",
    color = "Direction"
  ) +
  theme_classic() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1),
    aspect.ratio = 1
  ) +
  scale_color_manual(values = EV1_mix_A$factorColors$diffProp_Perturbation)

lineA1 + lineA2
```

### B Line

```{r, fig.width=10, fig.height=4}
DF_long <- as.data.frame(EV1_mix_B$proportion) %>%
  mutate(Direction = EV1_mix_B$testBarcodes$diffProp_Perturbation$results$direction) %>%
  pivot_longer(cols = -Direction, names_to = "SampleName", values_to = "Prop") 
target_replicated <- bind_rows(replicate(nrow(EV1_mix_B$proportion), EV1_mix_B$metadata, simplify = FALSE)) %>% 
  mutate(
    BarcodeID = rep(paste0("Barcode_", seq_len(nrow(EV1_mix_B$proportion))), each=nrow(EV1_mix_B$metadata))) 

DF_long <- bind_cols(DF_long, target_replicated) 


lineB1 <- ggplot(DF_long, 
       aes(x = Perturbation, y = Prop, 
           group = paste(BarcodeSize, BarcodeID), color = Direction)) +
  geom_line(alpha=0.6) +
  geom_point() +
  labs(
    title = "Prop vs Perturbation for Different Barcode and Barcode Sizes",
    x = "Perturbation Level",
    y = "Proportion",
    color = "Direction"
  ) +
  theme_classic() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1),
    aspect.ratio = 1
  ) +
  scale_color_manual(values = EV1_mix_B$factorColors$diffProp_Perturbation)

lineB2 <- ggplot(DF_long, 
       aes(x = Perturbation, y = log2(Prop*1000000+1), 
           group = paste(BarcodeSize, BarcodeID), color = Direction)) +
  geom_line(alpha=0.6) +
  geom_point() +
  labs(
    # title = "Prop vs Perturbation for Different Barcode and Barcode Sizes",
    x = "Perturbation Level",
    y = "log2(CPM+1)",
    color = "Direction"
  ) +
  theme_classic() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1),
    aspect.ratio = 1
  ) +
  scale_color_manual(values = EV1_mix_B$factorColors$diffProp_Perturbation)

lineB1 + lineB2
```

```{r}
mydata <- asin(sqrt(CPM_flag[1,]/1000000))

designMatrix <- model.matrix(
  formula("~Perturbation + BarcodeSize"), data = EV1_mix_B$metadata)

dup <- limma::duplicateCorrelation(
      object = mydata, design = designMatrix,
      block = repID
    )

dup$consensus.correlation

myfit1 <- limma::lmFit(
      object = mydata, design = designMatrix,
      block = repID, correlation = dup$consensus.correlation
    )

mycontrasts <- limma::makeContrasts(
        contrasts = paste0("Perturbation"),
        levels = colnames(designMatrix)
      )

myfit2 <- limma::contrasts.fit(fit = myfit1, contrasts = mycontrasts)

myfit3 <- limma::eBayes(myfit2)
  ## extract test result using multiple testing adjusted p.values
myresults <- limma::decideTests(myfit3, adjust.method = "BH")
direction <- dplyr::recode(as.vector(myresults),
    "1" = "increase",
    "-1" = "decrease", "0" = "n.s."
  )
rankedResults <- limma::topTable(myfit3, number = Inf, sort.by = "none")

```

