---
title: "negsim_perturb_barbieQ"
author: "LF"
date: "2025-05-12"
output: workflowr::wflow_html
output_dir: ../../DEBRA
---

# Load Dependencies

```{r load library, message=FALSE}
library(readxl)
library(magrittr)
library(dplyr)
library(tidyr) # for pivot_longer
library(tibble) # for rownames_to _column
library(knitr) # for kable()
library(ggplot2)
library(patchwork)
library(scales)
library(ggVennDiagram)
library(ComplexHeatmap)
library(limma)
library(edgeR)

library(SummarizedExperiment)
library(SEtools)
library(S4Vectors)
library(devtools)

# devtools::install_github("DaneVass/bartools", dependencies = TRUE, force = TRUE)
library(bartools)
```

# Install barbieQ - devel

```{r install barbieQ}
# devtools::install_github("Oshlack/barbieQ", force = TRUE)
# 
library(barbieQ)
```

# Load rds

```{r save rds}
# rda saved in "../../analysis/DEBRA/perturb_preprocessing.Rmd"

# # correct the `Subset` proporty of the two premix samples
# load("../../output/DEBRA/perturb_barbieQ.rda")
# perturb_top$sampleMetadata$Subset <- as.character(perturb_top$sampleMetadata$Subset)
# perturb_top$sampleMetadata$Subset[which(colnames(perturb_top) == "P1")] <- "premix1"
# perturb_top$sampleMetadata$Subset[which(colnames(perturb_top) == "P2")] <- "premix2"
# perturb_top$sampleMetadata$Subset <- factor(perturb_top$sampleMetadata$Subset,
#                                             levels = c("premix1", "premix2", "null", "perturb"))
# perturb_top$sampleMetadata
# 
# perturb$sampleMetadata$Subset <- as.character(perturb$sampleMetadata$Subset)
# perturb$sampleMetadata$Subset[which(colnames(perturb) == "P1")] <- "premix1"
# perturb$sampleMetadata$Subset[which(colnames(perturb) == "P2")] <- "premix2"
# perturb$sampleMetadata$Subset <- factor(perturb$sampleMetadata$Subset,
#                                             levels = c("premix1", "premix2", "null", "perturb"))
# perturb$sampleMetadata
# # save to rda
# save(perturb, perturb_top, file = "../../output/DEBRA/perturb_barbieQ.rda")

## load the corect rda
load("../../output/DEBRA/perturb_barbieQ.rda")
```

## t-SNE

```{r tsne}
## Set an appropriate perplexity value (e.g., num_samples / 3)
set.seed(12)
perplexity_value <- min(30, floor(ncol(perturb_top) / 3))

tsne_results <- (assays(perturb_top)$CPM + 1) %>%
  t() %>%
  log2() %>%
  Rtsne::Rtsne(perplexit = perplexity_value)
tsne_coords <- tsne_results$Y
tsne_coords <- as.data.frame(tsne_coords)

ggplot(tsne_coords) +
  geom_point(aes(x = V1, y = V2, col = perturb_top$sampleMetadata$Subset)) +
  labs(x = "t-SNE Dimension 1", y = "t-SNE Dimension 2", col = "Subset") +
  theme_classic() +
  theme(aspect.ratio = 1)

lapply(
  perturb_top$sampleMetadata %>% ncol() %>% seq(),
  function(i) {
    col_fac <- colnames(perturb_top$sampleMetadata)[i]
    ggplot(tsne_coords) +
     geom_point(aes(x = V1, y = V2, col = perturb_top$sampleMetadata[[i]])) +
     labs(x = "t-SNE Dimension 1", y = "t-SNE Dimension 2", color = col_fac) +
      theme_classic() +
     theme(aspect.ratio = 1)
  }
  )

perturb_top <- perturb_top[,perturb_top$sampleMetadata$Subset != "premix"]

pca_results <- (assays(perturb_top)$CPM + 1) %>% 
  t() %>% 
  log2() %>% 
  prcomp( scale. = TRUE)

pca_df <- data.frame(
  PC1 = pca_results$x[, 1],
  PC2 = pca_results$x[, 2],
  Subset = perturb_top$sampleMetadata$Subset
)

ggplot(pca_df, aes(x = PC1, y = PC2, color = Subset)) +
  geom_point(size = 3) +
  labs(title = "PCA on logCPM", x = "PC1", y = "PC2") +
  theme_classic() +
  theme(aspect.ratio = 1)

perturb_top$sampleMetadata %>% as.data.frame() %>%  View()
assay(perturb_top) %>% colnames()
```

## bartools

```{r bartools, fig.width=30, fig.height=10}
load("../../output/DEBRA/perturb_barbieQ.rda")

ps.counts <- assay(perturb_top)

perturb_dge <- DGEList(
  counts = ps.counts, 
  group = perturb_top$sampleMetadata$Subset)

bartools::plotBarcodeHistogram(perturb_dge)
```

# Test Perturbation

```{r perturb}
colnames(perturb_top)
perturb_top$sampleMetadata %>% as.data.frame() %>% summary()

mixed <- perturb_top[, perturb_top$sampleMetadata$Subset %in% c("perturb", "null")]
mixed$sampleMetadata

mixed_add1 <- createBarbieQ(object = assay(mixed) +1, sampleMetadata = mixed$sampleMetadata)

mixed_target <- mixed$sampleMetadata %>% as.data.frame()
# mixed_add1_target$Perturbation <- as.factor(mixed_add1_target$Perturbation)
mixed_target$BarcodeSize <- as.factor(mixed_target$BarcodeSize)
mixed_design <- mixed_target %>%
    with(model.matrix(~0 + Perturbation + BarcodeSize))

mixed_add1 <- testBarcodeSignif(
  barbieQ = mixed_add1, sampleMetadata = mixed_target, sampleGroup = "Perturbation",
  designMatrix = mixed_design)

bar_test <- rowData(mixed_add1)$testingBarcode
bar_test %>% as.data.frame() %>% View()
metadata(bar_test)$design
bar_test$direction %>% table()
bar_test$meanDiff %>% summary()

plotBarcodeMA(mixed_add1)
# ggsave("../../output/DEBRA/true_MA_add1_add1.png", dpi = 300, plotBarcodeMA(mixed_add1))
plotBarcodePValue(mixed_add1)

## too many rows
# plotSignifBarcodeHeatmap(perturb_top)
plotSignifBarcodeProportion(mixed_add1)

rowData(perturb_top)$testingBarcode <- rowData(mixed_add1)$testingBarcode
metadata(perturb_top) <- metadata(mixed_add1)
plotSignifBarcodeProportion(perturb_top)

# ggsave("../../output/DEBRA/true_sig_prop_add1.png", dpi = 300, plotSignifBarcodeProportion(perturb_top))


## manually check testing results
## compare high perturb sample with low
colnames(perturb_top)
## validate using the premix pools
pool1 <- assays(perturb_top[,"P1"])$proportion
pool2 <- assays(perturb_top[,"P2"])$proportion
## color by mix testing results
perturb.Trend <- rowData(mixed_add1)$testingBarcode$tendencyTo
p_validate <- ggplot(data.frame(pool1 = pool1, pool2 = pool2)) +
  geom_point(aes(x = (pool1 + pool2), y = (pool1 - pool2), color  = perturb.Trend)) +
  scale_color_manual(values = metadata(mixed_add1)$factorColors$testingBarcode) +
  theme_classic() +
  theme(aspect.ratio = 1)

p_validate
# ggsave("../../output/DEBRA/true_pools_add1.png", dpi = 300, p_validate)

N1 <- sum((as.vector(pool1)  - as.vector(pool2) ) > 0.0001)
N2 <- sum((as.vector(pool2)  - as.vector(pool1) ) > 0.0001)

n1 <- sum(rowData(mixed_add1)$testingBarcode$direction == 1)
n2 <- sum(rowData(mixed_add1)$testingBarcode$direction == -1)

n1 / N1
n2 / N2

## very limited improvement by adding 1
```

```{r fig.width=10, fig.height=5}
mixed <- perturb_top[, perturb_top$sampleMetadata$Subset %in% c("perturb", "null")]
mixed_dge <- DGEList(
  counts = assay(mixed), 
  group = mixed$sampleMetadata$Subset)
bartools::plotBarcodeHistogram(mixed_dge)

perturbed <- perturb_top[, perturb_top$sampleMetadata$Subset %in% c("perturb")]

perturbed_dge <- DGEList(
  counts = assay(perturbed[,order(perturbed$sampleMetadata$Perturbation)]), 
  group = perturbed$sampleMetadata$Subset[order(perturbed$sampleMetadata$Perturbation)])
bartools::plotBarcodeHistogram(perturbed_dge)
```


# Subet Null Samples

```{r subset dmso}
nulls <- perturb_top[, perturb_top$sampleMetadata$Subset == "null"]

## plot props using bartools
nulls_dge <- DGEList(
  counts = assay(nulls), 
  group = nulls$sampleMetadata$Subset
)
bartools::plotBarcodeHistogram(nulls_dge)
ggsave(filename = "../../output/DEBRA/bartool_nulls.png", 
       dpi = 300, width = 8, height = 6, plot = bartools::plotBarcodeHistogram(nulls_dge))  

## check prop distribution, max
AM_nulls <- data.frame(Mean = assays(nulls)$proportion %>% rowMeans())
AM_nulls %>% summary()

props <-  assays(nulls)$proportion %>% as.vector()
props %>% summary()

ggplot(data.frame(props = props)) +
  geom_histogram(aes(x = props))

ggplot(AM_nulls) +
  geom_histogram(aes(x = Mean))

```

## NegSim

```{r negsim dmso, fig.width=7, fig.height=5}
source("../../analysis/bartools_dose_escalation/NegSim.R")

library(SummarizedExperiment)
library(magrittr)
library(barbieQ)
library(ggplot2)
library(patchwork)

load("../../output/DEBRA/perturb_barbieQ.rda")

nulls <- perturb_top[, perturb_top$sampleMetadata$Subset == "null"]

## add 1 as an offset
nulls <- createBarbieQ(assay(nulls) +1)

set.seed(2025)

results_negsi <- random_sampling(barbieQ = nulls, loop_times = 100)

## saved to global
## initially saved as all_loops in all_loops.rda
save(global_all_loops, file = "../../output/DEBRA/all_loops_add1.rda")

lapply(results_negsi, plot)

results_negsi[[1]] <- results_negsi[[1]] + ggtitle("Prop_asin, perturb_null")
results_negsi[[2]] <- results_negsi[[2]] + ggtitle("Prop_logit, perturb_null")
results_negsi[[3]] <- results_negsi[[3]] + ggtitle("Prop_noTrans, perturb_null")
results_negsi[[4]] <- results_negsi[[4]] + ggtitle("Occ_firth, perturb_null")
results_negsi[[5]] <- results_negsi[[5]] + ggtitle("Prop_asin, perturb_null")
results_negsi[[6]] <- results_negsi[[6]] + ggtitle("Prop_logit, perturb_null")
results_negsi[[7]] <- results_negsi[[7]] + ggtitle("Prop_noTrans, perturb_null")
results_negsi[[8]] <- results_negsi[[8]] + ggtitle("Occ_firth, perturb_null")

ggsave(
  "../../output/DEBRA/tester_add1.png",
  wrap_plots(results_negsi[1:8], ncol = 4),
  width = 40, height = 15,
  units = "cm"
  )

```

## Inspect NegSim

### load results

```{r extract results from random sampling}
load("../../output/DEBRA/all_loops_add1.rda")

  # extract results from the loops
  end_sampling <- 6
  
  ## extract FPR
  all_FPR <- lapply(seq(3:end_sampling), function(n) {
    global_all_loops[[n]]$FPR
  })
  df_FPR <- do.call(rbind, all_FPR)
  
  ## extract P.Val
  all_P.Val <- lapply(seq(3:end_sampling), function(n) {
    global_all_loops[[n]]$P.Val
  })
  df_P.Val <- do.call(rbind, all_P.Val)
  
  ## extract MA
  all_MA <- lapply(seq(3:end_sampling), function(n) {
    global_all_loops[[n]]$MA
  })
  df_MA <- do.call(rbind, all_MA)
  
  all_Group_Vec <- lapply(seq(3:end_sampling), function(n) {
    global_all_loops[[n]]$Group_Vec
  })
  df_Group_Vec <- do.call(rbind, all_Group_Vec)
  
  stats_barcodes <- cbind(df_P.Val[,1:4], df_MA)

```

### MA plot

```{r inspect random sampling}
## LFC and Gmean works better than linear diff and Amean
## the x axis is actually log2 Gmean
ggplot(as.data.frame(df_MA)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop, 
                 color = as.factor(df_P.Val$Prop_asin < 0.05)))

ggplot(as.data.frame(df_MA)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop,  
                 color = as.factor(df_P.Val$Prop_logit < 0.05)))

ggplot(as.data.frame(df_MA)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop, 
                 color = as.factor(df_P.Val$Prop_noTrans < 0.05)))


## flag out the FPR-high simulation
flag_highFPR <- which(df_FPR$Prop_asin > 0.05)
SimID_highFPR <- df_FPR[flag_highFPR,]$SimulationID

# df_Group_Vec[SimID_highFPR,]


```

### P.Val vs. Prop

```{r plot p.val}
stats_barcodes <- cbind(df_P.Val[,1:4], df_MA)
# stats_barcodes$Gmean_prop <- (2^stats_barcodes$Gmean_prop-0.5) / 1e6

ggplot(stats_barcodes) +
  geom_point(aes(y = -log10(Prop_asin), x = log10(Amean_prop + 1e-7)), color = "skyblue", alpha = 0.6) +
  geom_point(aes(y = -log10(Prop_logit), x = log10(Amean_prop + 1e-7)), color = "yellow", alpha = 0.6) +
  geom_point(aes(y = -log10(Prop_noTrans), x = log10(Amean_prop + 1e-7)), color = "pink", alpha = 0.6) +
  geom_hline(yintercept = -log10(0.05))


```

```{r plot P.Val high}
temp_df <- stats_barcodes %>% filter(SimulationID %in% SimID_highFPR)

ggplot(temp_df) +
  geom_point(aes(y = -log10(Prop_asin), x = log10(Amean_prop + 1e-7)), color = "skyblue", alpha = 0.5) +
  geom_point(aes(y = -log10(Prop_logit), x = log10(Amean_prop + 1e-7)), color = "yellow", alpha = 0.5) +
  geom_point(aes(y = -log10(Prop_noTrans), x = log10(Amean_prop + 1e-7)), color = "pink", alpha = 0.5) +
  geom_hline(yintercept = -log10(0.05))
```


### Type I error rates

```{r type I error}
 # extract results from the loops
  ## extract FPR
  # all_FPR <- lapply(seq_along(3:end_sampling), function(n) {
  #   all_loops[[n]]$FPR
  # })
  # df_FPR <- do.call(rbind, all_FPR)
  # df_FPR$N_Samples <- as.factor(df_FPR$N_Samples)
  # ## extract P.Val
  # all_P.Val <- lapply(seq_along(3:end_sampling), function(n) {
  #   all_loops[[n]]$P.Val
  # })
  # df_P.Val <- do.call(rbind, all_P.Val)
  # df_P.Val$N_Samples <- as.factor(df_P.Val$N_Samples)
  
df_FPR$N_Samples <- as.factor(df_FPR$N_Samples)
  
  ## reshape the data to fit methods for testing
df_FPR_long <- df_FPR %>%
  pivot_longer(cols = starts_with("Prop_"),
               names_to = "Method",
               values_to = "Pval_Prop") %>%
  mutate(Method = factor(Method, levels = c("Prop_asin", "Prop_logit", "Prop_noTrans"),
                         labels = c("asin-sqrt", "logit", "no trans.")))

P_FPR_add1_prop <- ggplot(
  df_FPR_long, aes(x = factor(N_Samples), y = Pval_Prop, fill = factor(N_Samples))) +
  geom_boxplot(outlier.shape = 1, position = position_dodge(width = 0.7)) +
  # geom_jitter(size = 1, position = position_dodge(width = 0.7)) +
  geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
  # coord_cartesian(ylim = c(0, 0.2)) + 
  labs(title = "Differential proportion test under transformations",
       y = "Proportion of barcodes with p-value < 0.05",
       x = "Number of samples per group") +
  facet_wrap(~Method, scales = "free_y") +
  theme_classic() +
  theme(legend.position = "none")



ggsave(
  "../../output/DEBRA/tester_add1_prop.png",
  P_FPR_add1_prop,
  width = 20, height = 10,
  units = "cm"
  )

```




### Binned P.Val vs. Prop

#### Function

```{r bin Amean}
plotP.Val_binnedAmean <- function(stats_barcodes) {
  stats_binned <- stats_barcodes %>%
    mutate(
    logAmean = log10(Amean_prop + 1e-7),
    bin = cut(logAmean, breaks = seq(-7, -1, by = 1), include.lowest = TRUE)
  ) %>% 
    pivot_longer(
      cols = c(Prop_asin, Prop_logit, Prop_noTrans),
      names_to = "method",
      values_to = "pvalue"
    ) %>%
    mutate(neglog10_p = -log10(pvalue))

ggplot(stats_binned, aes(x = bin, y = neglog10_p, fill = method)) +
  geom_boxplot(alpha = 0.6, position = position_dodge(width = 0.8), outliers = F) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  facet_wrap(~ N_Samples, nrow = 1) +
  labs(x = "log10(barcode mean prop.) bins", y = "-log10(p-value)", fill = "Method") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```


```{r bin Amean, fig.width=12, fig.height=4}
plotP.Val_binnedAmean(stats_barcodes)
ggsave("../../output/DEBRA/p.val_binned_add1.png", dpi = 300, height = 4, width = 12,
       plotP.Val_binnedAmean(stats_barcodes))
```

```{r bin Amean high-FPR, fig.width=10, fig.height=8}
temp_df <- stats_barcodes %>% filter(SimulationID %in% SimID_highFPR)
plotP.Val_binnedAmean(temp_df)
```

### Median P.Val

```{r median}
plot_median_P.Val <- function(stats_barcodes) {

  stats_binned <- stats_barcodes %>%
    mutate(
      logAmean = log10(Amean_prop + 1e-7),
      bin = cut(logAmean, breaks = seq(-7, -1, by = 1), include.lowest = TRUE)
    ) %>% 
    pivot_longer(
      cols = c(Prop_asin, Prop_logit, Prop_noTrans),
      names_to = "method",
      values_to = "pvalue"
    ) %>%
    mutate(neglog10_p = -log10(pvalue))

  # Compute medians per bin/method/N_Samples
  median_lines <- stats_binned %>%
    group_by(bin, method, N_Samples) %>%
    summarize(median_neglog10_p = median(neglog10_p, na.rm = TRUE), .groups = "drop")

  # Plot
  ggplot(stats_binned, aes(x = bin, y = neglog10_p, fill = method)) +
    # geom_boxplot(alpha = 0.6, position = position_dodge(width = 0.8), outliers = F) +
    # geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
    geom_point(
      data = median_lines, aes(x = bin, y = median_neglog10_p, group = method, color = method), size = 1.8) +
    geom_line(
      data = median_lines, aes(x = bin, y = median_neglog10_p, group = method, color = method), linewidth = 0.8) +
    facet_wrap(~ N_Samples, nrow = 1) +
    labs(
      x = "log10(barcode mean prop.) bins",
      y = "-log10(median P-value)",
      fill = "Method",
      color = "Method"
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top")
}

plot_median_P.Val(stats_barcodes)


```

```{r}
ggsave("../../output/DEBRA/median_p.val.png", dpi = 300, width = 8, height = 3,
       plot_median_P.Val(stats_barcodes))
```


### QQ plot

```{r qq function}
qq_plot_pvalues <- function(stats_barcodes) {
  df <- stats_barcodes %>%
    select(Prop_asin, Prop_logit) %>%
    filter(!is.na(Prop_asin), !is.na(Prop_logit)) %>%
    arrange(Prop_asin) %>%
    mutate(
      expected = -log10(ppoints(n())),
      observed_asin = -log10(Prop_asin[order(Prop_asin)]),
      observed_logit = -log10(Prop_logit[order(Prop_logit)])
    )

  ggplot(df, aes(x = expected)) +
    geom_point(aes(y = observed_asin, color = "asin-sqrt"), alpha = 0.5) +
    geom_point(aes(y = observed_logit, color = "logit"), alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
    scale_color_manual(values = c("asin-sqrt" = "#d95f02", "logit" = "#1b9e77")) +
    labs(
      x = "Expected -log10(p)",
      y = "Observed -log10(p)",
      color = "Method",
      title = "QQ Plot of Differential Proportion p-values"
    ) +
    theme_minimal()
}

qq_plot_pvalues(stats_barcodes) + theme(aspect.ratio = 1)

ggsave("../../output/DEBRA/qq_trans.png", dpi = 300, 
       qq_plot_pvalues(stats_barcodes) + theme(aspect.ratio = 1))

## just to plot q-quantiles
  df <- stats_barcodes %>%
    select(Prop_asin, Prop_logit) %>%
    filter(!is.na(Prop_asin), !is.na(Prop_logit)) %>%
    arrange(Prop_asin) %>%
    mutate(
      observed_asin = -log10(Prop_asin[order(Prop_asin)]),
      observed_logit = -log10(Prop_logit[order(Prop_logit)])
    )

  ggplot(df) +
    geom_point(aes(x = observed_logit, y = observed_asin), alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
    labs(
      x = "Observed -log10(p) using asin-sqrt",
      y = "Observed -log10(p) using logit",
      title = "QQ Plot of p-values: logit against asin-sqrt"
    ) +
    theme_minimal()+
    coord_fixed()
```


### High FPR simulation

#### locate the high FPRs

```{r high asin}
flag_highFPR_asin <- which(df_FPR$Prop_asin > 0.06)
df_FPR[flag_highFPR_asin,"SimulationID"]

flag_highFPR_logit <- which(df_FPR$Prop_logit > 0.2)
df_FPR[flag_highFPR_logit,"SimulationID"]

flag_highFPR_noTrans <- which(df_FPR$Prop_noTrans > 0.05)
df_FPR[flag_highFPR_noTrans, "SimulationID"]

View(df_FPR[flag_highFPR_noTrans,])

## simulation groups
## happen to belong to two groups of high / low library size: 660, 330, 160 or 80, 40, 20
df_Group_Vec[flag_highFPR_asin,]
df_Group_Vec[flag_highFPR_logit,]
df_Group_Vec[flag_highFPR_noTrans,]

```

#### union of the high FPR

```{r high union}
flag_highFPR_union <- union(union(flag_highFPR_asin, flag_highFPR_logit), flag_highFPR_noTrans)

SimID_highFPR <- df_FPR[flag_highFPR_union, "SimulationID"]

stats_barcodes_SimHigh <- stats_barcodes %>% filter(SimulationID %in% SimID_highFPR)

ggplot(stats_barcodes_SimHigh) +
  geom_point(aes(x = -log10(Prop_asin), y = -log10(Prop_logit))) +
  coord_fixed() +
  geom_vline(xintercept = -log10(0.05)) +
  geom_hline(yintercept = -log10(0.05))

ggplot(stats_barcodes_SimHigh) +
  geom_point(aes(x = -log10(Prop_asin), y = -log10(Prop_noTrans))) +
  coord_fixed() +
  geom_vline(xintercept = -log10(0.05)) +
  geom_hline(yintercept = -log10(0.05))


ggplot(as.data.frame(stats_barcodes_SimHigh)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop, 
                 color = as.factor(Prop_asin < 0.05)))

ggplot(as.data.frame(stats_barcodes_SimHigh)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop, 
                 color = as.factor(Prop_logit < 0.05)))

ggplot(as.data.frame(stats_barcodes_SimHigh)) +
  geom_point(aes(x = Gmean_prop, y = LFC_prop, 
                 color = as.factor(Prop_noTrans < 0.05)))
```

#### Function

```{r heatmap of high sim}
groups_highFPR <- df_Group_Vec[flag_highFPR_union,]

plotSimHeatmap <- function(sim) {
  ## the first dim is "sample_3_loop_29"
  ## add simulation groups to sample metadata
  nulls <- perturb_top[, perturb_top$sampleMetadata$Subset == "null"]
  ## add 1 as an offset
  nulls <- createBarbieQ(object = assay(nulls) +1, sampleMetadata = nulls$sampleMetadata)
  simData <- nulls
  simData$sampleMetadata <- cbind(simData$sampleMetadata, t(groups_highFPR[sim,, drop = F]))
  ## locate the barcode pvalues of the chosen simulation
  check_barcodes <- stats_barcodes_SimHigh %>% 
    filter(SimulationID == sim) 
  ## locate the significant barcodes in either test
  sig_barcodes <- which(check_barcodes$Prop_asin < 0.05 | check_barcodes$Prop_logit< 0.05 | check_barcodes$Prop_noTrans < 0.05)
  
  sig_simData <- simData[sig_barcodes,]
  barbieQ::plotBarcodeHeatmap(barbieQ = sig_simData, splitSamples = T, sampleGroup = sim, barcodeAnnotation = rowAnnotation(
    asin = check_barcodes[sig_barcodes,"Prop_asin"] < 0.05,
    logit = check_barcodes[sig_barcodes,"Prop_logit"] < 0.05,
    noTrans = check_barcodes[sig_barcodes,"Prop_noTrans"] < 0.05,
    col = list(
      asin = c(`TRUE` = "red", `FALSE` = "grey"),
      logit = c(`TRUE` = "red", `FALSE` = "grey"),
      noTrans = c(`TRUE` = "red", `FALSE` = "grey")
    )
    ))
}

```

#### heatmap

```{r, fig.width=30, fig.height=30}
Heatmeap_list <- lapply(rownames(groups_highFPR), plotSimHeatmap)

# Set the resolution and output file for PNG
png("../../output/DEBRA/heatmap_highFPR_simulation_add1.png", width = 30, height = 30, units = "in", res = 300)

# Set layout: 2 rows × 2 columns
n_rows <- 6
n_cols <- 5

grid.newpage()
pushViewport(viewport(layout = grid.layout(n_rows, n_cols)))

vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

for (i in seq_along(Heatmeap_list)) {
  row <- ceiling(i / n_cols)
  col <- (i - 1) %% n_cols + 1
  pushViewport(vplayout(row, col))
  draw(Heatmeap_list[[i]], newpage = FALSE)  # This renders the heatmap in the current viewport
  upViewport()
}

# Close the PNG device
dev.off()
```

#### tsne / pca

```{r pca high FPR simulation}
groups_highFPR <- df_Group_Vec[flag_highFPR_union,]

plotSimPCA <- function(sim) {
  ## the first dim is "sample_3_loop_29"
  ## add simulation groups to sample metadata
  simData <- nulls
  simData$sampleMetadata <- cbind(simData$sampleMetadata, t(groups_highFPR[sim,, drop = F]))
  ## locate the barcode pvalues of the chosen simulation
  check_barcodes <- stats_barcodes_SimHigh %>% 
    filter(SimulationID == sim) 
  ## locate the significant barcodes in either test
  sig_barcodes <- which(check_barcodes$Prop_asin < 0.05 | check_barcodes$Prop_logit< 0.05 | check_barcodes$Prop_noTrans < 0.05)
  
  pca_results <- prcomp(t(assays(simData)$proportion))
  ggplot(as.data.frame(pca_results$x)) +
    geom_point(aes(x = PC1, y = PC2, color = groups_highFPR["sample_3_loop_29",]))
  
  tsne_results <- Rtsne(t(assays(simData)$proportion), perplexity = 3)
  ggplot(as.data.frame(tsne_results$Y)) +
    geom_point(aes(x = V1, y = V2, color = groups_highFPR["sample_3_loop_29",]))
  
  umap_results <- umap(t(assays(simData)$proportion), 
                       n_neighbors = 3, min_dist = 0.1, metric = "euclidean")
  ggplot(as.data.frame(umap_results)) +
    geom_point(aes(x = V1, y = V2, color = groups_highFPR["sample_3_loop_29",]))
}

```
