---
title: "Analysis on public barcode count datasets"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Project Aim

This project collects public barcode count datasets and analyses them using the  [barbieQ](https://github.com/Oshlack/barbieQ) package. - Liyang, Jan 2025

# Analyses in the barbieQ paper

|**Figure**|**Content** |**Source** |
|---|---|---|
|Figure 1 |Package flowchart |*./output/barbieQ_figure1.drawio.png* |
|[Figure 2](barbieQ_paper_Figure2.html) |Example of preprocessing | |
|[Figure 3 and Figure S3](barbieQ_paper_Figure3.html) |Statistical tests (Type I and II error rate) | |
|[Figure 4](barbieQ_paper_Figure4.html) |Case study | |
| | | |

# Datasets

## BelderbosME [README](../data/BelderbosME/README.md)
 
## bartools_dose_escalation [README](../data/bartools_dose_escalation/README.md)
 
## DEBRA (README file not ready yet)
 
## WuC (README file not ready yet)

 - Explore filtering strategies by comparing filtered and unfiltered data regarding statistical test results on barcode differential proportion. [filtering_explore_alter](WuC/filtering_explore_alter.html)

 - When selecting NK-biased clones, compare the performance of barbieQ and the paper's strategy based on the paper's validation method. [compare_original_analysis](WuC/compare_original_analysis.html)
