---
title: "Neg_sim"
author: "LF"
date: "2024-05-31"
output: html_document
---


# Load Library

```{r load library}
library(readxl)
library(purrr)
library(dplyr)
library(dbscan)
library(ggbiplot)
library(gridExtra)
library(ComplexHeatmap)
library(Rtsne)
library(dbscan)
library(rpart)
library(rpart.plot)
library(pROC)
library(sjPlot)
library(glmnet)
library(logistf)

# Define the directory containing the R files - Barbie 
directory <- "/Users/feiliyang/Desktop/Barbie/R"

# Get the list of R files in the directory
file_list <- list.files(directory, pattern = "\\.R$", full.names = TRUE)

# Loop through each file and load it
for (file in file_list) {
  source(file)
}
```

# Read Object

```{r read data}
Belderbos <- readRDS(file = "/Users/feiliyang/Desktop/published_analysis_tools/barcodetrackRData/datasets/BelderbosME_etal/Belderbos_Barbie.RDS")
```


# Trim Data

```{r trim data}
del_out <- Belderbos$metadata$Time %in% c("library", "time0")

# |Belderbos$metadata$Mouse == "C23"
Belderbos_hem <- trimColumn(Barbie = Belderbos, keep_columns = !del_out)

Belderbos_hem <- getTopBar(Barbie = Belderbos_hem, cut_off = 0.90, num_appearance = 2)

sum(Belderbos_hem$is_top)

Belderbos_hem <- trimRow(Barbie = Belderbos_hem, keep_rows = Belderbos_hem$is_top)

# Get a logical vector indicating duplicated rows
duplicated_samp <- duplicated(t(Belderbos_hem$CPM))
unique_samp <- !duplicated_samp

#trim the obj
Belderbos_uniqueCol<- trimColumn(Barbie = Belderbos_hem, keep_columns = unique_samp)
```

# Pseudo Replicate Groups

Pseudo replicate groups:
1. Mouse == C21
2. Mouse == C22
3. Mouse == C23
4. Mouse == C10 | C15 & Celltype == Unsorted | Tcell
5. Mouse == C10 | C15 & Celltype == Bcell | Grn | Other
6. Mouse == C1 | C2 | C3 & Time == sac
7. Mouse == C1 & Time == live 
8. Mouse == C2 | C3 & Time == live & Celltype == Unsorted
9. Mouse == C2 | C3 & Time == live & Celltype == Bcell | Tcell | Grn

```{r pseudo rep}
meta <- Belderbos_uniqueCol$metadata

meta$pseudo_group[meta$Mouse == "C21"] <- "C21"
meta$pseudo_group[meta$Mouse == "C22"] <- "C22"
meta$pseudo_group[meta$Mouse == "C23"] <- "C23"
meta$pseudo_group[
  meta$Mouse %in% c("C10", "C15") 
  & meta$Celltype %in% c("Unsorted", "Tcell")] <- "C10.15_U.T"
meta$pseudo_group[
  meta$Mouse %in% c("C10", "C15") 
  & meta$Celltype %in% c("Bcell", "Grn", "Other")] <- "C10.15_B.G.O"
meta$pseudo_group[
  meta$Mouse %in% c("C1", "C2", "C3") 
  & meta$Time == "sac"] <- "C1.2.3_sac"
meta$pseudo_group[
  meta$Mouse == "C1" 
  & meta$Time != "sac"] <- "C1.live"
meta$pseudo_group[
  meta$Mouse %in% c("C2", "C3") 
  & meta$Time != "sac"
  & meta$Celltype == "Unsorted"] <- "C2.3_live_U"
meta$pseudo_group[
  meta$Mouse %in% c("C2", "C3") 
  & meta$Time != "sac"
  & meta$Celltype %in% c("Bcell", "Tcell", "Grn")] <- "C2.3_live_B.T.G"
```

# Sampling within Pseudo-Groups

Fixed Sample Size

```{r sampling fixed size}
set.seed(42) # for reproducibility

# function for sampling once making two equal groups
Sample_Groups <- function(Barbie, size_group = 3) {
  
  pool <- Barbie$metadata %>% nrow() %>% seq()
  
  # First sampling without replacement
  group1_samples <- sample(pool, size = size_group, replace = FALSE)
  # Remove the first sample from the pool
  remaining_pool <- setdiff(pool, group1_samples)
  
  # Second sampling without replacement from the remaining pool
  group2_samples <- sample(remaining_pool, size = size_group, replace = FALSE)
  
  # Create a group vector
  group_vec <- vector("character", length = length(pool))
  group_vec[group1_samples] <- "group1"
  group_vec[group2_samples] <- "group2"
  
  Barbie$metadata$group <- group_vec
  
  # Hem data by group vector
  sample_bb <- trimColumn(
    Barbie = Barbie,
    keep_columns = group_vec %in% c("group1", "group2")
  )
  
  c_table_i <- GetContingencyTable(
    Barbie = sample_bb,
    Vector_customized = sample_bb$metadata$group)
  
  sample_bb <- GetOccBiasGroup(Barbie = sample_bb, contingency_table_ls = c_table_i)
  
  mytargets <- data.frame(sample_bb$metadata)
  
  # model design matrix
  mydesign <- mytargets %>%
    with(model.matrix(~0 + group))
  
  # set up block
  myblock <- NULL
  
  # apply test for Bias_Prop
  sample_bb <- getPropBiasGroup(Barbie = sample_bb, mydesign = mydesign, myblock = myblock, mytargets = mytargets)
  
  #logistic model
  sample_bb <- GetLogitOcc(Barbie = sample_bb, penalized = F)
  
  #penalized logistic madel
  sample_bb <- GetLogitOcc(Barbie = sample_bb, penalized = T)
  
  # extract p.values and FPR
  pvalues_occ <- sample_bb$Bias_Occ$pvalue
  pvalues_prop <- sample_bb$Bias_Prop$pvalue
  pvalues_LR_occ_classic <- sample_bb$LR_Occ_classic$p.values
  pvalues_LR_occ_penalized <- sample_bb$LR_Occ_penalized$p.values
  
  FPR_occ <- sum(sample_bb$Bias_Occ$group != "Unbiased") / length(sample_bb$Bias_Occ$group)
  
  FPR_prop <- sum(sample_bb$Bias_Prop$group != "Unbiased") / length(sample_bb$Bias_Prop$group)
  
  FPR_LR_occ_classic <- sum(sample_bb$LR_Occ_classic$group != "Unbiased") / length(sample_bb$LR_Occ_classic$group)
  
  FPR_LR_occ_penalized <- sum(sample_bb$LR_Occ_penalized$group != "Unbiased") / length(sample_bb$LR_Occ_penalized$group)
  
  return(
    list(FPR_occ = FPR_occ,
         FPR_prop = FPR_prop,
         FPR_LR_occ_classic = FPR_LR_occ_classic,
         FPR_LR_occ_penalized = FPR_LR_occ_penalized,
         pvalues_occ = pvalues_occ,
         pvalues_prop = pvalues_prop,
         pvalues_LR_occ_classic = pvalues_LR_occ_classic,
         pvalues_LR_occ_penalized = pvalues_LR_occ_penalized,
         group_vec = group_vec)
  )

}

Loop_Samples <- function(Barbie, size_group = 3, loop_times = 100) {
  
  FPR_occ_list <- list(length = loop_times)
  FPR_prop_list <- list(length = loop_times)
  FPR_LR_occ_classic_list <- list(length = loop_times)
  FPR_LR_occ_penalized_list <- list(length = loop_times)
  
  pvalues_occ_list <- list(length = loop_times)
  pvalues_prop_list <- list(length = loop_times)
  pvalues_LR_occ_classic_list <- list(length = loop_times)
  pvalues_LR_occ_penalize_list <- list(length = loop_times)
  
  group_vec_list <- list(length = loop_times)
  
  for(i in 1:loop_times) {
    results_i <- Sample_Groups(
      Barbie = Barbie, size_group = size_group)
    
    FPR_occ_list[[i]] <- results_i$FPR_occ
    FPR_prop_list[[i]] <- results_i$FPR_prop
    FPR_LR_occ_classic_list[[i]] <- results_i$FPR_LR_occ_classic
    FPR_LR_occ_penalized_list[[i]] <- results_i$FPR_LR_occ_penalized
    
    pvalues_occ_list[[i]] <- results_i$pvalues_occ
    pvalues_prop_list[[i]] <- results_i$pvalues_prop
    pvalues_LR_occ_classic_list[[i]] <- results_i$pvalues_LR_occ_classic
    pvalues_LR_occ_penalize_list[[i]] <- results_i$ pvalues_LR_occ_penalize
    
    group_vec_list[[i]] <- results_i$group_vec
  }
  
  FPR <- data.frame(
    N_Samples = rep(size_group, loop_times),
    Occ = FPR_occ_list %>% unlist(),
    Prop = FPR_prop_list %>% unlist(),
    LR_occ_classic = FPR_LR_occ_classic_list %>% unlist(),
    LR_occ_penalized = FPR_LR_occ_penalized_list %>% unlist()
    )
  
  pvalues <- data.frame(
    N_Samples = rep(size_group, loop_times),
    Occ = pvalues_occ_list %>% unlist(),
    Prop = pvalues_prop_list %>% unlist(),
    LR_occ_classic = pvalues_LR_occ_classic_list %>% unlist(),
    LR_occ_penalized = pvalues_LR_occ_penalize_list %>% unlist()
    )
  
  return(list(
    FPR = FPR,
    pvalues = pvalues,
    group_vec_list = group_vec_list))

}

```

```{r random sampling C22}

# run the loop for each size of samples
random_sampling <- function(Barbie) {

  num_samples <- ncol(Barbie$CPM)
  end_sampling <- floor(num_samples / 2)
  
  # stop running loop if end_sampling <= 3
  if(num_samples < 3) {
    return("not enough samples!")
  }
  
  set.seed(42) # for reproducibility
  
  # run the loops
  all_loops <- lapply(3:end_sampling, function(n) {
    Loop_Samples(
      Barbie = Barbie, size_group = n, loop_times = 2)
  })
  
  # extract results from the loops
  all_FPR <- lapply(seq(3:end_sampling), function(n) {
    all_loops[[n]]$FPR
  }) 
  
  df_FPR <- do.call(rbind, all_FPR)
  
  df_FPR$N_Samples <- as.factor(df_FPR$N_Samples)
  
  all_pvalue <- lapply(seq(3:end_sampling), function(n) {
    all_loops[[n]]$pvalues
  })
  
  df_pvalues <- do.call(rbind, all_pvalue)
  
  df_pvalues$N_Samples <- as.factor(df_pvalues$N_Samples)
  
  gFDRocc <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = Occ, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility +
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Occ, Mouse C22",
         y = "Prop. barcodes with p.value < 0.05",
         x = "No. samples per group") +
    theme_classic()
  
  gFDRLRocc_c <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = LR_occ_classic, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility +
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Logit_Occ_classic, Mouse C22",
         y = "Prop. barcodes with p.value < 0.05",
         x = "No. samples per group") +
    theme_classic()
  
  gFDRLRocc_p <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = LR_occ_penalized, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility +
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Logit_Occ_penalized, Mouse C22",
         y = "Prop. barcodes with p.value < 0.05",
         x = "No. samples per group") +
    theme_classic()
  
  gFDRprop <- ggplot(as.data.frame(df_FPR),
    aes(x = N_Samples, y = Prop, fill = N_Samples)) +
    # geom_violin(width = 0.5) +  # Set width for better visibility
    geom_boxplot(width = 0.5, outlier.shape = NA) +
    geom_jitter(width = 0.1, height = 0, size = 1) +  # Add jittered points
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Prop, Mouse C22",
         y = "Prop. barcodes with p.value < 0.05",
         x = "No. samples per group") +
    theme_classic()
  
  
  gPocc <- ggplot(as.data.frame(df_pvalues),
    aes(x = N_Samples, y = Occ, fill = N_Samples)) +
    geom_violin(width = 0.5) +
    geom_jitter(width = 0.1, height = 0, size = 1) +
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Occ, Mouse C22",
         y = "p.value")
  
  gPprop <- ggplot(as.data.frame(df_pvalues),
    aes(x = N_Samples, y = Prop, fill = N_Samples)) +
    geom_violin() +
      geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
    labs(title = "Diff_Prop, Mouse C22",
         y = "p.value")
  
  return(
    list(gFDRocc = gFDRocc,
         gFDRLRocc_c = gFDRLRocc_c,
         gFDRLRocc_p = gFDRLRocc_p,
         gFDRprop = gFDRprop,
         gPocc = gPocc,
         gPprop = gPprop))

}


# Calculate the combos
for(i in 3:8) {
  print(choose(17,i) * choose(17-i,i))
}

```

# C22 

```{r C22 tsne}
C22_bb <- trimColumn(
  Barbie = Belderbos_uniqueCol,
  keep_columns = meta$pseudo_group == "C22")

results_negsi <- random_sampling(Barbie = C22_bb)

lapply(results_negsi, plot)

# color samples by random groups
flagN4 <- all_loops[[2]]$FPR$Occ > 0.05
group_vec_N4 <- all_loops[[2]]$group_vec_list[flagN4]

flagN8 <- all_loops[[6]]$FPR$Occ > 0.05
group_vec_N8 <- all_loops[[6]]$group_vec_list[flagN8]

flagN3 <- all_loops[[1]]$FPR$Prop > 0.05
group_vec_N3 <- all_loops[[1]]$group_vec_list[flagN3]

# function for plotting random groups
color_rd_group <- function(group_info){
  ggplot(tsne_coords) +
  geom_point(aes(x = V1, y = V2, col = group_info,
                 shape = group_info), size = 3) +
  labs(x = "t-SNE Dimension 1", y = "t-SNE Dimension 2", col = "Random Group", shape = "Random Group") +
  theme_classic() +
  theme(aspect.ratio = 1) +
  scale_color_manual(
    values = c("grey", "group1" = "red", "group2" = "blue")) +
  scale_shape_manual(
    values = c(16,17,17)
  )
}

# plot sig. simulations
lapply(list(group_vec_N4[[1]],
            group_vec_N4[[2]],
            group_vec_N8[[1]],
            group_vec_N3[[1]],
            group_vec_N3[[2]],
            group_vec_N3[[3]]),
       function(x) {
        color_rd_group(x)
      })

# Unsorted subset has 10 samples in total.
for(i in 3:5) {
  print(choose(10,i) * choose(10-i,i))
}
```

### C22 details

```{r C22 details, fig.width=10, fig.height=7}
# subset of sig. simulations
C22_bb$metadata$group <- group_vec_N3[[2]]
NegSim_gp <- trimObjectByMetadata(
  Barbie = C22_bb,
  condition = "group",
  specified = c("group1", "group2"),
  keep = TRUE
)

ConTb_N3_1<- GetContingencyTable(
  Barbie = NegSim_gp,
  Factor = "group"
)

NegSim_gp <- GetOccBiasGroup(
  Barbie = NegSim_gp,
  contingency_table_ls = ConTb_N3_1
)

mytargets <- data.frame(NegSim_gp$metadata)
  
# model design matrix
mydesign <- mytargets %>%
    with(model.matrix(~0 + group))
  
# set up block
myblock <- NULL
  
# apply test for Bias_Prop
NegSim_gp <- getPropBiasGroup(
  Barbie = NegSim_gp, 
  mydesign = mydesign, 
  myblock = myblock, 
  mytargets = mytargets)

row_ha <- NegSim_gp %>% with(
  rowAnnotation(
    Prop = Bias_Prop$group,
    Occ = Bias_Occ$group,
    col = list(
      Prop = color_panel$bias_group,
      Occ = color_panel$bias_group
      ),
    show_legend = TRUE,
    show_annotation_name = TRUE,
    annotation_name_side = "bottom",
    annotation_name_gp = gpar(fontsize = 10)
    )
)

PlotCpmHP_0(
  Barbie = NegSim_gp,
  Vector_customized = NegSim_gp$metadata$group,
  show_bias = TRUE,
  row_ha = row_ha
  ) 

pointer_N3_1 <- NegSim_gp$Bias_Occ$group != "Unbiased"

NegSim_gp$Bias_Prop$group[pointer_N3_1]

ConTb_N3_1[pointer_N3_1]



# Example data:
#            Response
# Treatment   Yes No
# Treatment1  3  0
# Treatment2  0  3

# Creating the table in R
contingency_table <- matrix(c(0, 3, 3, 0), nrow = 2, byrow = TRUE)

# Add row and column names (optional, but helps with readability)
dimnames(contingency_table) <- list(
  Treatment = c("Treatment1", "Treatment2"),
  Response = c("Yes", "No")
)

# Print the table
print(contingency_table)

# Perform Fisher's Exact Test
fisher.test(contingency_table)

chisq.test(contingency_table)
```
